### ISSUE TITLE
[BUG] Loading Card Not Opening

### ISSUE THREAD

**Issue by SalvatoreITA** [flixlix/energy-flow-card-plus#30]
Hello , thanks for your great work I have updated and I only have a loading notice without the card display.

![556](https://github.com/flixlix/energy-flow-card-plus/assets/74460788/573895df-6ef6-4c29-8e76-9a7e1033057a)

![8989](https://github.com/flixlix/energy-flow-card-plus/assets/74460788/392a844c-0ccc-451a-8172-02738499088d)

**Comment by flixlix** [comment]
Hi, thank you very much!

Which version are you running? This was an issue in an older version.

**Comment by SalvatoreITA** [comment]
I'm using the latest version 0.0.2.3, I also tried on another instance of home assistant same problem.


![111111](https://github.com/flixlix/energy-flow-card-plus/assets/74460788/e95fd890-6f2e-430f-ad10-bab052dbe1d9)

**Comment by flixlix** [comment]
That screenshot is from my other card 😅
Do you have the energy integration setup?

**Comment by SalvatoreITA** [comment]
sorry i posted the screenshot wrong
![555](https://github.com/flixlix/energy-flow-card-plus/assets/74460788/76dd72ab-b60c-4c64-834e-20aaade3e51a)

**Comment by flixlix** [comment]
Do you have the energy integration setup?

**Comment by SalvatoreITA** [comment]
![65656](https://github.com/flixlix/energy-flow-card-plus/assets/74460788/f95a45d1-5a5b-4259-b314-3ab82c9fa458)
Yes

**Comment by flixlix** [comment]
Ok that's weird then.

Can you set 
```yaml
energy_date_selection: false
```
?

**Comment by SalvatoreITA** [comment]
![6666666666](https://github.com/flixlix/energy-flow-card-plus/assets/74460788/dce13e1d-fd09-49b0-98c6-4de8a459454f)
Now it works but the fossil remains at 0

**Comment by flixlix** [comment]
What version did you have before that worked?
I am not experiencing this. It looks like the card is not getting the energy data like it should

**Comment by SalvatoreITA** [comment]
v0.0.2.2.2, Maybe it's a bug of my home assistant, is it possible to make the card independent from the energy board also as regards the fossil part?

**Comment by flixlix** [comment]
I just remembered! Make sure you have a Energy Period Selector in the same dashboard, then it should work.

You can use [this one](https://www.home-assistant.io/dashboards/energy/#energy-date-picker) or, may I recommend [my own card](https://github.com/flixlix/energy-period-selector-plus) 😅

I think I'll add this as disclaimer instead of loading...

Regarding the non fossil part without any energy date picker: This wasn't possible up until now, but I created a PR #32 allowing this behavior 😊 Thank you for the suggestion.

Does it work for you as well now?

**Comment by flixlix** [comment]
![Bildschirmfoto 2023-05-29 um 21 20 26](https://github.com/flixlix/energy-flow-card-plus/assets/61006057/d94cf935-9e38-4612-a7b2-c5c3314b64c2)
Update: added this. Will be available in the next version (not v0.0.2.4 yet)

**Comment by SalvatoreITA** [comment]
Works great now thanks! I would be grateful if you could make the fossil part independent of the official energy card in the next updates.

Do you have a link where you can make a paypal donation?

**Comment by flixlix** [comment]
> I would be grateful if you could make the fossil part independent of the official energy card in the next updates.

Will do 😊


You can donate in these different places 🥰:
* https://ko-fi.com/flixlix
* https://github.com/sponsors/flixlix
* https://www.paypal.com/donate/?hosted_button_id=9T4CR9XPTJKD8
