### ISSUE TITLE
[BUG] Custom element doesn't exist (Mobile App only)

### ISSUE THREAD

**Issue by lukibazuki** [flixlix/energy-flow-card-plus#35]
First, thank you for your great contributions, they are really great. 

Here my issue:
The Card shows up properly on the desktop version (also on Safari via the iPhone) but not on the Mobile App. I am using the latest version of the card, v.0.0.2.4

This is the desktop version:
<img width="255" alt="image" src="https://github.com/flixlix/energy-flow-card-plus/assets/24279405/a9e41de7-3882-4cc6-9fba-f7a3fb8b6ee8">

Here on the official iPhone App
![IMG_3069 2023-05-30 14_38_19](https://github.com/flixlix/energy-flow-card-plus/assets/24279405/59a870bd-c5ad-4bb8-a15a-7625e44791f7)

I have tried to add it to the configuration.yaml file, with no positive effect. 
<img width="193" alt="image" src="https://github.com/flixlix/energy-flow-card-plus/assets/24279405/e1d9d370-bce8-4098-b20a-84915e5a4745">

Note that I do have no issues whatsoever with the Power Flow Card Plus. 

I am running 
Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.2
Frontend 20230503.3 - latest

**Comment by flixlix** [comment]
This seems to be a cache issue.
AFAIK there's no way to clear the cache on iPhone apart from deleting and reinstalling the HA app.
Can you try opening this view in a dashboard that you've never used for HA?

**Comment by lukibazuki** [comment]
You are right, this did the trick. You are awesome 👍
