### ISSUE TITLE
[OTHER] I can't install the Card

### ISSUE THREAD

**Issue by jove01** [flixlix/energy-flow-card-plus#38]
Hello
I installed your Power Card and it works fine.
Now I want to install the Energy Card for daily Information. but it disn't works.

I have download the your Hacs and added the Resources via dashbord (but without hacstag?)
By Adding a new ard:
![grafik](https://github.com/flixlix/energy-flow-card-plus/assets/116289742/639b89db-26a5-436a-9d68-8fa92751b63a)

Also by custom the card.

I hope, you can helo to show what is wrong.
Thank you 
Jürgen

**Comment by flixlix** [comment]
Hey Jürgen, can you try adding a period selector to this dashboard, or click on the card and set `energy_date_selection: false`?

**Comment by jove01** [comment]
Hey Felix
Thanks for the quick answer.
I tried it during my test

**Comment by flixlix** [comment]
Can you send me the code that you tried?

**Comment by jove01** [comment]
Hey
here is my last  Code
`type: custom:energy-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.daily_direct_energy_consumption
      production: sensor.daily_exported_energy_compensation
    use_metadata: false
    display_zero_tolerance: 10
    display_state: two_way
  home: {}
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
energy_date_selection: false
wh_decimals: 1
kwh_decimals: 0
min_flow_rate: 1
max_flow_rate: 6
max_expected_energy: 2000
min_expected_energy: 10
wh_kwh_threshold: 1000
title: Tag`

When I in Edit-Mode  i see the Card
<img width="247" alt="image" src="https://github.com/flixlix/energy-flow-card-plus/assets/116289742/3d0fcd10-d466-4c46-87be-00582a598a5d">

Whe I close the Edit Mode, I don't see the Card.

**Comment by flixlix** [comment]
Do you have any errors showing in the browser console?
What version is showing there?

**Comment by jove01** [comment]
I  deleted all cards, files and reposository, then i start again and installed all 3 cards. Tomorrow i will finish all, but i think it works fine. 
Thank you
