### ISSUE TITLE
[OTHER] Template doesn't work 

### ISSUE THREAD

**Issue by flyzet-prog** [flixlix/energy-flow-card-plus#39]
Hi dear developer. Trying to multiply sensor value to some number, but it won't show up, non either on secondary info. It's still shows entity instead of template value.
Please check bellow:
<img width="1150" alt="Screenshot 2023-06-05 at 17 37 13" src="https://github.com/flixlix/energy-flow-card-plus/assets/73076482/129eefa5-1df2-41fd-a9fb-46ce730c644e">
<img width="894" alt="Screenshot 2023-06-05 at 17 35 44" src="https://github.com/flixlix/energy-flow-card-plus/assets/73076482/621de9cf-d2b0-4246-81cc-eda93474c8f8">

Please help me to Fix this.

**Comment by flixlix** [comment]
Hi, 
Unfortunately, templates are not **YET** supported for this card.
I'll try adding this feature in the future

**Comment by flyzet-prog** [comment]
Thank you for your reply. Probably I’ve already managed to that with help of template sensors, but can you please help me to add the feature to count the price by days, week, month etc. ?Exactly like energy counts already.

**Comment by flyzet-prog** [comment]
Thank you for your reply. Probably I’ve already managed to that with help of template sensors, but can you please help me to add the feature to count the price by days, week, month etc. ?Exactly like energy counts already.
![0815B9DD-6FA1-4023-B86D-1AE404E6AC7D](https://github.com/flixlix/energy-flow-card-plus/assets/73076482/e396775d-5f08-4101-abc7-238385f181e3)
![91B44A27-4054-4F0C-89C0-683328058343](https://github.com/flixlix/energy-flow-card-plus/assets/73076482/60bf5c08-1495-4b54-8bf3-9e1850cc474e)

**Comment by flyzet-prog** [comment]
If it's possible please add feature statistic for secondary info by day, week, month etc. Would be much upreciated. Thank you for your efforts

**Comment by flixlix** [comment]
>If it's possible please add feature statistic for secondary info by day, week, month etc. Would be much upreciated. Thank you for your efforts

I like this idea, I'll try adding this in the near future.
atm I'm very very busy, so it's unfortunately not going to be in the next days

**Comment by flixlix** [comment]
Just released version 0.1!

With it comes the functionality to toggle `energy_date_selection` for secondary fields! 🥳
This feature is also available in the UI-Editor 🚀

**Comment by flyzet-prog** [comment]
> Just released version 0.1!
> 
> With it comes the functionality to toggle `energy_date_selection` for secondary fields! 🥳 This feature is also available in the UI-Editor 🚀

Thank you for your efforts. I will test it out in 1 hour when it's updated, and let you know if everything is correct. But found  one issue already, when I click on the secondary info of home it shows me the same value as the main info. This only appears only on HOME

**Comment by flyzet-prog** [comment]
> > Just released version 0.1!
> > With it comes the functionality to toggle `energy_date_selection` for secondary fields! 🥳 This feature is also available in the UI-Editor 🚀
> 
> Thank you for your efforts. I will test it out in 1 hour when it's updated, and let you know if everything is correct. But found one issue already, when I click on the secondary info of home it shows me the same value as the main info. This only appears only on HOME

Hello dear developer. I Have been tested secondary info with my sensors, and it won’t track them every hour, day etc. always see zero. The sensors updates as should be. 
please help me to resolve this issue.
