### ISSUE TITLE
s.entries is not a function [BUG]

### ISSUE THREAD

**Issue by nejc-cc** [flixlix/energy-flow-card-plus#40]
**Describe the bug**
Visual editor doesn't work, only YAML. I get the following error:

> s.entries is not a function

**To Reproduce**
1. try to add a new card and you get this message in Card Configuration

**Expected behavior**
Well I thought it might be able to avoid YAML if possible 🙂 

**Screenshots**
![image](https://github.com/flixlix/energy-flow-card-plus/assets/38460081/c27bc4b7-4eb5-4949-818e-2defaa923c0d)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Firefox
 - Version: 113.0.2

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
This issue is caused by Card Mod. I've added a Warning in the Readme to make others aware of the issue:

> ⚠️ This card also has a UI-Editor. This Editor is currently incompatible with Card Mod. I created a PR to fix this issue, but it hasn't been merged yet. Here is the [PR #277](https://github.com/thomasloven/lovelace-card-mod/pull/277). Since it hasn't been merged yet, I also released a fork with the changes from the PR. Installing this Version of Card Mod you can use this card in conjunction with Card Mod. [Here is my fork](https://github.com/flixlix/lovelace-card-mod)

**Comment by nejc-cc** [comment]
Ooooh that's what that meant. Got it, thank you :)

**Comment by flixlix** [comment]
You're welcome :)
