### ISSUE TITLE
[FEATURE REQUEST] Secondary info shows decimals

### ISSUE THREAD

**Issue by bodawui** [flixlix/energy-flow-card-plus#53]
for some time it was working, but now it shows only full numbers.

I used decimals: 2 parameter, but now it seems as not available on secondary info object.

is it possible to add it?

Use Case:
On Grid tile I' would like to display price, but this shows like 1 or 2...which makes a big different if you have 1,4 or 1,5.

**Comment by flixlix** [comment]
Added this option in the yaml as well as in the UI Editor 🥳
Will be available in the next version

**Comment by flyzet-prog** [comment]
> le I' would like to display price

Do you use energy_date_selection: true on secondary info? Does it track secondary info by days, weeks, month etc.?
