### ISSUE TITLE
[OTHER] Transparent background for Circles.

### ISSUE THREAD

**Issue by rcenik** [flixlix/energy-flow-card-plus#6]
Love the new energy card. Could you make this one have transparent backgrounds as well? So it matches the Power card.

When you did the power card it also made the card slightly bigger. You can see in the Screenshot. It would be nice if both matched up perfectly.

<img width="1661" alt="Screenshot 2023-05-13 at 12 40 23 PM" src="https://github.com/flixlix/energy-flow-card-plus/assets/64944957/c2ee6d7b-7361-4b24-851f-0a447f293d16">

**Comment by flixlix** [comment]
Thank you very much for your support, it was especially a lot of work figuring out how to get the card to sync with the date selector 😅
It will probably occur a lot of times, where I have one bugfix or new feature on one card and have to "sync up" the other card, but I'm fine with that

I will gladly add this bugfix to this card when I get the time to do so 😊

**Comment by flixlix** [comment]
Fixed in version 0.0.1.1 🙂
