### ISSUE TITLE
[FEATURE REQUEST] More than 2 Individual items

### ISSUE THREAD

**Issue by mhuiskes** [flixlix/energy-flow-card-plus#62]
In my setup I have more than two energy meters; I'd like to display all on the Energy Flow Card Plus 

**Describe the solution you'd like**
Each should have its own circle. These would all connect to the circle of the house.

**Describe alternatives you've considered**
The Energy Card shows a horizontal bar graph. The benefit is that this can show many consumers. Unfortunately the scale is shared for all, so big and small users are mixed. This isn't ideal. Also I prefer the visualisation with the circles
<img width="709" alt="MockUp" src="https://github.com/flixlix/energy-flow-card-plus/assets/92112296/bb5b25b9-f0b9-42a8-9dee-b9ebbb3b3430">

**Comment by flixlix** [comment]
This is not currently planned
