### ISSUE TITLE
[BUG] wrong data displayed

### ISSUE THREAD

**Issue by Destroyer061090** [flixlix/energy-flow-card-plus#70]
**Describe the bug**

**To Reproduce**
just installed the new version and setup thashold Mwh to Kwh to 1000 with decimal 2 and the all value are display directly in Mwh (not showing anymore Kwh)

**Expected behavior**
I expect:
when value before 1000 watt then value should be shown in watt
when value above 1000 watt but below 1000 kwh then value should be shown in kwh
when value above 1000 kwh then the value should be shown in Mwh

**Screenshots**
previous version (v0.1.1) year:
![immagine](https://github.com/flixlix/energy-flow-card-plus/assets/126196958/0855de46-4656-4788-ad01-32be8e72d29d)
new version year (OK):
![immagine](https://github.com/flixlix/energy-flow-card-plus/assets/126196958/49a204a7-1317-4018-b84e-f9129df61731)
previous version (v0.1.1) today:
![immagine](https://github.com/flixlix/energy-flow-card-plus/assets/126196958/a9ceb7ca-e019-4515-a0fd-a0cc3f6287c8)
new version today (NOT OK):
![immagine](https://github.com/flixlix/energy-flow-card-plus/assets/126196958/9a3ebdd2-19f2-4960-b9a8-4986ca7442ac)

**Desktop (please complete the following information):**
 - latest version of mozilla firefox

**Smartphone (please complete the following information):**
 iphone 14 Pro with version 16.6

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [ x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-flow-card-plus/discussions)).

- [ x] I have the latest version of the card installed.

- [ x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Sorry for the inconvenience, fixed the issue in 0.1.2.1 👍

**Comment by Destroyer061090** [comment]
Hello, Would you implement also in the water meter when above 1000L it becomes in m3 automatically?
