### ISSUE TITLE
[BUG] HACS not offering the latest v0.1.2.1 release

### ISSUE THREAD

**Issue by erikgeurts** [flixlix/energy-flow-card-plus#71]
**Describe the bug**
The release of v0.1.2, followed soon after by v0.1.2.1 while at the same time unpublishing v0.1.2 appears to have confused HACS, at least for me. Both v0.1.2 and v0.1.2.1 do not show up as an available update in HACS.

**To Reproduce**
I still have/had v0.1.1 installed, I saw the notification about v0.1.2 but before I got around to updating, I saw v0.1.2.1 being published on Github, v0.1.2 disappeared in HACS but v0.1.2.1 did not show up in HACS.

I also noticed that v0.1.2.1 is displayed as the latest release on the main Github page at https://github.com/flixlix/energy-flow-card-plus but when I go to releases, at https://github.com/flixlix/energy-flow-card-plus/releases , the newest displayed there is still v0.1.2 and it's marked as "Pre-release". I'm guessing that somehow the two releases in a very short time frame with the second being a hot fix for the first, caused some confusion in Github's release list.

**Expected behavior**
I would expect v0.1.2.1 to appear in HACS automatically.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: tried multiple including Windows and ChromeOS
 - Browser: Chrome
 - Version: v115

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-flow-card-plus/discussions)).

- [ ] I have the latest version of the card installed.
Actually no, since that's the issue I'm reporting.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Hey, I also noticed this weird behavior.
But since in GitHub the release 0.1.2.1 is set as latest, there is nothing I can do to fix it, this seems like rather a bug with HACS...
Let's hope the next release gets revealed in HACS

**Comment by erikgeurts** [comment]
Have a  look at https://github.com/flixlix/energy-flow-card-plus/releases where you can see that v0.1.2.1 was not created as a release, it only shows up as a tag at https://github.com/flixlix/energy-flow-card-plus/tags .

I think somehow the creation of the v0.1.2.1 release didn't work properly in Github.

Perhaps something to look at, so that people get the newest release in HACS after all.

**Comment by flixlix** [comment]
Both links show v0.1.2.1 as the latest release.

**Comment by erikgeurts** [comment]
Nope:
![image](https://github.com/flixlix/energy-flow-card-plus/assets/5102461/dc312014-f28a-4241-96d8-d6f348917f55)

**Comment by flixlix** [comment]
![Screenshot_20230812_142501_Firefox.jpg](https://github.com/flixlix/energy-flow-card-plus/assets/61006057/062143d9-6dac-4b54-bca5-bc48480c48ee)

![Screenshot_20230812_142507_GitHub.jpg](https://github.com/flixlix/energy-flow-card-plus/assets/61006057/4a57151b-0427-447a-ad43-a629cabd5f4b)

Each Link

**Comment by erikgeurts** [comment]
Whatever I do (all devices I have, incognito mode, cache cleared, and so on), at https://github.com/flixlix/energy-flow-card-plus/releases all I see v0.1.2 as the most recent release.

Where does that second screenshot come from?

**Comment by flixlix** [comment]
I tried with incognito and also can't see the latest release. 
After putting the latest release 0.1.2.1 as a beta version and latest version back again, the issue seems to be fixed now. It also shows as the latest version in HACS if you redownload it. You might have to wait for the update to show up automatically in the main HACS page.
Sorry for the inconvenience but this issue seems to have been related to the GitHub release system

**Comment by erikgeurts** [comment]
It did the trick for me! Thanks for your assistance.
