### ISSUE TITLE
Only configurations with "battery" working.

### ISSUE THREAD

**Issue by Hummelchen01** [flixlix/energy-flow-card-plus#9]
- also the 2 samples without battery will not work. (only white card)

The power-flow-card-plus works for me perfect.
But with "energy" i stuck with this problem.

Thanks for your very good work.

**Comment by flixlix** [comment]
Hi @Hummelchen01. Can you please explain what your issue is?

**Comment by Hummelchen01** [comment]
Hello Luca,

Thanks for the quick reaktion.
I think the cause starts with the fact that in my home assistant:
- Power-flow-card-plus works 100% and also looks very good.
- with Power-flow-card-plus nothing works if no "BATTERY" is included.
- the two examples in the documentation "Only Grid" and "Grid and Solar" only show a white card.
*********************************
              type: custom:energy-flow-card-plus
              entities:
                 grid:
                   entities:
                     consumption: sensor.grid_consumed_energy_daily
                     production: sensor.grid_returned_energy_daily
              wh_kwh_threshold: 0
*********************************
              type: custom:energy-flow-card-plus
              entities:
                 grid:
                   entities:
                     consumption: sensor.grid_consumed_energy_daily
                     production: sensor.grid_returned_energy_daily
                 solar:
                   entity: sensor.solar_energy_daily
              wh_kwh_threshold: 0
*********************************

**However, the 3rd example "Grid, Solar and Battery" in the documentation works as described:**
*********************************
              type: custom:energy-flow-card-plus
              entities:
                 grid:
                   entities:
                     consumption: sensor.grid_consumed_energy_daily
                     production: sensor.grid_returned_energy_daily
                 solar:
                   entity: sensor.solar_energy_daily
                 **batteries:
                   entities:
                     consumption: sensor.battery_out_energy_daily
                     production: sensor.battery_in_energy_daily**
              wh_kwh_threshold: 0
*********************************

What I can tell so far is that as soon as a battery is included, the display is correct except that I can't bring in any second information in "Home".

Greetings from Austria
Roland

**Comment by Hummelchen01** [comment]
Sorry...
with Power-flow-card-plus nothing works if no "BATTERY" is included.
Correct:
with **ENERGY**-flow-card-plus nothing works if no "BATTERY" is included.

**Comment by flixlix** [comment]
Thanks for pointing this bug out and thank you for providing more information.
I hadn't noticed that issue before, since I only used this card with a battery entity.
Luckily this was an easy fix, so it's already up. I'll release a new version with this fix, since this is very important to have fixed
